[workspace]
members = [
    "cangjie-mcp",
    "cangjie-mcp-cli",
    "cangjie-mcp-server",
    "cangjie-mcp-test",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "z"
